[package]
name = "gameboy-emu"
version = "0.1.0"
authors = ["Jorik Cronenberg <jcronenberg@suse.de>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
